### ISSUE TITLE
No sound during playback

### ISSUE THREAD

**Issue by riker09** [alexkdeveloper/raddiola#5]
Hello and first of all thank you for your mission: I'm still searching for a minimalistic internet radio player for Elementary OS (or *any* Linux Desktop) that is "not in the way". Yours is looking very promising.

I discovered it through the AppCenter start page, btw.

The issue I have is that playback won't start. I just freshly installed it via AppCenter, opened the app, added my favorite internet radio station (Soma FM Digitalis: https://somafm.com/digitalis130.pls) and full of optimism clicked the play button. But the headphones remained silent. I tried one of the stations that came with the program (Dubstep) and it stayed quiet as well, so it seems like a more general issue?

Please let me know if I can be of any further assistance.

**Comment by alexkdeveloper** [comment]
> Hello and first of all thank you for your mission: I'm still searching for a minimalistic internet radio player for Elementary OS (or _any_ Linux Desktop) that is "not in the way". Yours is looking very promising.
> 
> I discovered it through the AppCenter start page, btw.
> 
> The issue I have is that playback won't start. I just freshly installed it via AppCenter, opened the app, added my favorite internet radio station (Soma FM Digitalis: https://somafm.com/digitalis130.pls) and full of optimism clicked the play button. But the headphones remained silent. I tried one of the stations that came with the program (Dubstep) and it stayed quiet as well, so it seems like a more general issue?
> 
> Please let me know if I can be of any further assistance.

Hi! Unfortunately, the program does not support the pls format. It needs the addresses of the radio station streams. I found this list:
https://gist.github.com/sowcow/dd8e3de389398b013ee24eb318b23dd7
I checked several links and everything worked for me! Do you have all the built-in stations not working? Not all stations may work, but it depends on the stations themselves. If possible, I will periodically update the application and update this list.

**Comment by riker09** [comment]
Hello again. Yes, I can confirm that downloading the PLS file and opening it in an editor reveals something like this:

```
[playlist]
numberofentries=4
File1=http://ice4.somafm.com/digitalis-128-aac
Title1=SomaFM: Digitalis (#1): Digitally affected analog rock to calm the agitated heart.
Length1=-1
File2=http://ice2.somafm.com/digitalis-128-aac
Title2=SomaFM: Digitalis (#2): Digitally affected analog rock to calm the agitated heart.
Length2=-1
File3=http://ice6.somafm.com/digitalis-128-aac
Title3=SomaFM: Digitalis (#3): Digitally affected analog rock to calm the agitated heart.
Length3=-1
File4=http://ice1.somafm.com/digitalis-128-aac
Title4=SomaFM: Digitalis (#4): Digitally affected analog rock to calm the agitated heart.
Length4=-1
Version=2
```

I picked the first URL from that file `http://ice4.somafm.com/digitalis-128-aac` and edited my station. Playback works now.
